table 'Calendar'
    lineageTag: 8db9d15c-b4bf-446e-87fd-c6498d430367
    description: Auto-generated Calendar table for time intelligence
    isHidden

    partition 'Calendar' = m
        mode: import
        source
            let
                StartDate = 'Date'[StartOfYear]('List'[Min]('Dim Customer'[Created Date])),
                EndDate = 'Date'[EndOfYear]('List'[Max]('Dim Customer'[Created Date])),
                DateList = 'List'[Dates](StartDate, 'Duration'[Days](EndDate - StartDate) + 1, #duration(1,0,0,0)),
                #"Convert to Table" = 'Table'[FromList](DateList, 'Splitter'[SplitByNothing](), {{"Date"}}),
                #"Changed Type" = 'Table'[TransformColumnTypes](#"Convert to Table", {{"Date", type date}}),
                #"Added Year" = 'Table'[AddColumn](#"Changed Type", "Year", each 'Date'[Year]([Date]), 'Int64'[Type]),
                #"Added Quarter" = 'Table'[AddColumn](#"Added Year", "Quarter", each 'Date'[QuarterOfYear]([Date]), 'Int64'[Type]),
                #"Added Month" = 'Table'[AddColumn](#"Added Quarter", "Month", each 'Date'[Month]([Date]), 'Int64'[Type]),
                #"Added MonthName" = 'Table'[AddColumn](#"Added Month", "MonthName", each 'Date'[MonthName]([Date]), type text),
                #"Added Day" = 'Table'[AddColumn](#"Added MonthName", "Day", each 'Date'[Day]([Date]), 'Int64'[Type]),
                #"Added DayOfWeek" = 'Table'[AddColumn](#"Added Day", "DayOfWeek", each 'Date'[DayOfWeek]([Date], 'Day'[Monday]) + 1, 'Int64'[Type]),
                #"Added DayName" = 'Table'[AddColumn](#"Added DayOfWeek", "DayName", each 'Date'[DayOfWeekName]([Date]), type text)
            in
                #"Added DayName"

    column Date
        dataType: dateTime
        lineageTag: 1ac31401-7abf-4d81-96aa-40d2f07c7723
        formatString: yyyy-MM-dd
        sourceColumn: Date
        summarizeBy: none

    column Year
        dataType: int64
        lineageTag: 262432c2-8ab4-48fb-beab-1b1f8c84c92f
        formatString: 0
        sourceColumn: Year
        summarizeBy: none

    column Quarter
        dataType: int64
        lineageTag: 0389486e-fdfe-4d41-8dbd-a6cfcd6e978d
        formatString: 0
        sourceColumn: Quarter
        summarizeBy: none

    column Month
        dataType: int64
        lineageTag: eeed58a0-314d-4445-b984-195548b8a222
        formatString: 0
        sourceColumn: Month
        summarizeBy: none

    column MonthName
        dataType: string
        lineageTag: 8d0c23ca-0ab3-49f5-bd20-9c6a889c336c
        sourceColumn: MonthName
        sortByColumn: Month
        summarizeBy: none

    column Day
        dataType: int64
        lineageTag: a9fbe7f4-e19b-42de-863b-f539fc96bf00
        formatString: 0
        sourceColumn: Day
        summarizeBy: none

    column DayOfWeek
        dataType: int64
        lineageTag: ca20dc04-3507-4f15-b0bf-831491372648
        formatString: 0
        sourceColumn: DayOfWeek
        summarizeBy: none

    column DayName
        dataType: string
        lineageTag: 14d426de-c3d8-48c0-9d47-ecf5575414f9
        sourceColumn: DayName
        sortByColumn: DayOfWeek
        summarizeBy: none

    hierarchy 'Date Hierarchy'
        lineageTag: 9f06a15b-145a-4e9d-9bf9-b3249ef9b5f1
        level Year
            lineageTag: e1006720-3ace-4582-8777-72589111bc13
            column: Year
        level Quarter
            lineageTag: ae315c28-c604-4818-825f-3fd19a9c2b83
            column: Quarter
        level Month
            lineageTag: fc5f62e0-57b1-40e1-b958-e6be4e18e365
            column: Month
        level Day
            lineageTag: c6e25776-ec88-4687-acfb-f43d945f5c94
            column: Day

    measure 'YTD Sales' = TOTALYTD(SUM('Calendar'[Date]), 'Calendar'[Date])
        lineageTag: 44e47728-e7bf-4787-a3e3-c6f82a37876f
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Time Intelligence
        description: YTD aggregate — replace SUM('Calendar'[Date]) with your actual measure

    measure 'PY Sales' = CALCULATE([YTD Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
        lineageTag: b7dc07d5-11f4-4dbd-b971-ad75d6885954
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Time Intelligence
        description: Prior Year — references YTD Sales measure

    measure 'YoY %' = DIVIDE([YTD Sales] - [PY Sales], [PY Sales], BLANK())
        lineageTag: e6ce69b2-041c-44a7-8e0d-3360f04a67e4
        formatString: 0.00%
        displayFolder: Time Intelligence
        description: Year-over-Year percentage change

    /// @migration: unreferenced-hidden — consider removing
