table 'Calendar'
    lineageTag: 0424de01-256e-4aec-8696-a9b49aa5ad2b
    description: Auto-generated Calendar table for time intelligence
    isHidden

    partition 'Calendar' = m
        mode: import
        source
            let
                StartDate = 'Date'[StartOfYear]('List'[Min]('Dim Customer'[Created Date])),
                EndDate = 'Date'[EndOfYear]('List'[Max]('Dim Customer'[Created Date])),
                DateList = 'List'[Dates](StartDate, 'Duration'[Days](EndDate - StartDate) + 1, #duration(1,0,0,0)),
                #"Convert to Table" = 'Table'[FromList](DateList, 'Splitter'[SplitByNothing](), {{"Date"}}),
                #"Changed Type" = 'Table'[TransformColumnTypes](#"Convert to Table", {{"Date", type date}}),
                #"Added Year" = 'Table'[AddColumn](#"Changed Type", "Year", each 'Date'[Year]([Date]), 'Int64'[Type]),
                #"Added Quarter" = 'Table'[AddColumn](#"Added Year", "Quarter", each 'Date'[QuarterOfYear]([Date]), 'Int64'[Type]),
                #"Added Month" = 'Table'[AddColumn](#"Added Quarter", "Month", each 'Date'[Month]([Date]), 'Int64'[Type]),
                #"Added MonthName" = 'Table'[AddColumn](#"Added Month", "MonthName", each 'Date'[MonthName]([Date]), type text),
                #"Added Day" = 'Table'[AddColumn](#"Added MonthName", "Day", each 'Date'[Day]([Date]), 'Int64'[Type]),
                #"Added DayOfWeek" = 'Table'[AddColumn](#"Added Day", "DayOfWeek", each 'Date'[DayOfWeek]([Date], 'Day'[Monday]) + 1, 'Int64'[Type]),
                #"Added DayName" = 'Table'[AddColumn](#"Added DayOfWeek", "DayName", each 'Date'[DayOfWeekName]([Date]), type text)
            in
                #"Added DayName"

    column Date
        dataType: dateTime
        lineageTag: d1e38b58-3d27-4b17-8b74-745dca7c4d3f
        formatString: yyyy-MM-dd
        sourceColumn: Date
        summarizeBy: none

    column Year
        dataType: int64
        lineageTag: b8e27412-558d-43ea-9861-b957a0f50a44
        formatString: 0
        sourceColumn: Year
        summarizeBy: none

    column Quarter
        dataType: int64
        lineageTag: 6e7bf952-a791-4a46-88db-4c51b7adf1c1
        formatString: 0
        sourceColumn: Quarter
        summarizeBy: none

    column Month
        dataType: int64
        lineageTag: 87e2a3c2-0c8e-445a-ad05-690d46a0bc89
        formatString: 0
        sourceColumn: Month
        summarizeBy: none

    column MonthName
        dataType: string
        lineageTag: 6ba85ee7-67f7-46c3-b4e7-ff18e4f731f9
        sourceColumn: MonthName
        sortByColumn: Month
        summarizeBy: none

    column Day
        dataType: int64
        lineageTag: 1322f890-ff8f-473e-8bbf-52d1fba1bf98
        formatString: 0
        sourceColumn: Day
        summarizeBy: none

    column DayOfWeek
        dataType: int64
        lineageTag: 134f4e0c-57f1-47e1-9903-48b6a00cedf2
        formatString: 0
        sourceColumn: DayOfWeek
        summarizeBy: none

    column DayName
        dataType: string
        lineageTag: 25f69590-3290-424c-94d2-7d9e21f36ccf
        sourceColumn: DayName
        sortByColumn: DayOfWeek
        summarizeBy: none

    hierarchy 'Date Hierarchy'
        lineageTag: 387652e1-aee0-4a22-882d-faf818ece3ef
        level Year
            lineageTag: 92ee4e5b-a8e8-4d1e-a4bb-4ae006f8c84a
            column: Year
        level Quarter
            lineageTag: 3f919e4a-f8c4-41cc-8fb0-9cc31a073ffa
            column: Quarter
        level Month
            lineageTag: 935198a7-8027-4b68-b5b8-44f1fee0a9ac
            column: Month
        level Day
            lineageTag: b18870b1-239a-4b0e-b8a0-bc2ca44927a5
            column: Day

    measure 'YTD Sales' = TOTALYTD(SUM('Calendar'[Date]), 'Calendar'[Date])
        lineageTag: 351f3d00-54df-41a5-b14f-b737d702f1ff
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Time Intelligence
        description: YTD aggregate — replace SUM('Calendar'[Date]) with your actual measure

    measure 'PY Sales' = CALCULATE([YTD Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
        lineageTag: 2a04b241-2b67-4090-89e6-0149c11a99e5
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Time Intelligence
        description: Prior Year — references YTD Sales measure

    measure 'YoY %' = DIVIDE([YTD Sales] - [PY Sales], [PY Sales], BLANK())
        lineageTag: 5cfd5e9b-046f-475e-9c47-062ff9968978
        formatString: 0.00%
        displayFolder: Time Intelligence
        description: Year-over-Year percentage change

    /// @migration: unreferenced-hidden — consider removing
