table FACT_Payroll
    lineageTag: c1c1c67f-b9d2-483a-9ef3-8fe75bb547e5

    partition FACT_Payroll = m
        mode: import
        source
            let
                Source = 'Sql'[Database]("onelake-sql-endpoint", "MigrationLakehouse"),
                FACT_Payroll = Source{[Schema="dbo", Item="FACT_Payroll"]}[Data]
            in
                FACT_Payroll

    column 'Pay ID' = "PAYROLL"."PAY_ID"
        dataType: string
        lineageTag: 5dbe1b29-59ed-457d-a297-084e06d73729

    column 'Gross Pay' = "PAYROLL"."GROSS_PAY"
        dataType: string
        lineageTag: 6ba87a41-55bf-4c7a-bb2c-86172077d74d

    column 'Net Pay' = "PAYROLL"."GROSS_PAY" - "PAYROLL"."DEDUCTIONS"
        dataType: string
        lineageTag: d6666660-58b9-4688-8839-d47ebef0cd88

    measure 'Avg Salary' = AVERAGE('FACT_Payroll'["EMPLOYEES"."SALARY"])
        lineageTag: 22f90f81-0cc1-4ae0-b7b2-9191ad0ce493
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Measures

        /// @migration: broken-ref-auto-hidden
