table FACT_Orders
    lineageTag: 98ede5ae-1da1-4028-8960-dad05f04f2b6

    partition FACT_Orders = m
        mode: import
        source
            let
                Source = 'Sql'[Database]("onelake-sql-endpoint", "MigrationLakehouse"),
                FACT_Orders = Source{[Schema="dbo", Item="FACT_Orders"]}[Data]
            in
                FACT_Orders

    column 'Order ID' = "ORDERS"."ORDER_ID"
        dataType: string
        lineageTag: 6f5cae1e-0102-46ec-980f-a0ddebc557d7

    column 'Order Amount' = "ORDERS"."AMOUNT"
        dataType: string
        lineageTag: d53cacb8-c263-4afb-b9e5-1910aa48abeb

    measure 'FACT_Orders_Profit' = SUM('FACT_Orders'["ORDERS"."AMOUNT"]) * 0.2
        lineageTag: 84186d29-da1d-4448-86db-5ac470a38ffd
        formatString: #,0.00
        displayFolder: Measures

        /// @migration: broken-ref-auto-hidden
