table Sales
    lineageTag: 615c3358-891a-4a8a-a5a0-34bd70420e94

    partition Sales = m
        mode: import
        source
            let
                Source = 'Sql'[Database]("onelake-sql-endpoint", "MigrationLakehouse"),
                Sales = Source{[Schema="dbo", Item="Sales"]}[Data]
            in
                Sales

    column 'Quantity' = "FACT_SALES"."QUANTITY"
        dataType: string
        lineageTag: 8fac0950-6c49-4f68-b67e-019d863612fe

    measure 'Revenue' = SUM('Sales'["FACT_SALES"."QUANTITY" * "FACT_SALES"."UNIT_PRICE" * (1 - "FACT_SALES"."DISCOUNT_PCT"]))
        lineageTag: 779c846f-7bb4-44ba-89ed-1c33788e293f
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Measures

    measure 'Cost' = SUM('Sales'["FACT_SALES"."QUANTITY" * "DIM_PRODUCT"."UNIT_COST"])
        lineageTag: a735b288-2b5a-4f0e-8043-d4978d49028d
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Measures

    measure 'Profit' = SUM('Sales'["FACT_SALES"."QUANTITY" * "FACT_SALES"."UNIT_PRICE" * (1 - "FACT_SALES"."DISCOUNT_PCT"])) - SUM('Sales'["FACT_SALES"."QUANTITY" * "DIM_PRODUCT"."UNIT_COST"])
        lineageTag: bdf097b1-e959-4203-b0e8-f0c69f114270
        formatString: #,0.00
        displayFolder: Measures

    measure 'Profit Margin' = SWITCH(TRUE(),
    SUM('Sales'["FACT_SALES"."QUANTITY" * "FACT_SALES"."UNIT_PRICE"]) = 0, 0,
    (SUM('Sales'["FACT_SALES"."QUANTITY" * "FACT_SALES"."UNIT_PRICE" * (1 - "FACT_SALES"."DISCOUNT_PCT"])) - SUM('Sales'["FACT_SALES"."QUANTITY" * "DIM_PRODUCT"."UNIT_COST"])) / SUM('Sales'["FACT_SALES"."QUANTITY" * "FACT_SALES"."UNIT_PRICE"]) * 100
)
        lineageTag: ff3ed759-650f-47e2-8288-96538c843e22
        formatString: #,0.00
        displayFolder: Measures

    measure 'Return Rate' = SWITCH(TRUE(),
    SUM('Sales'["FACT_SALES"."QUANTITY"]) = 0, 0,
    SUM('Sales'["FACT_RETURNS"."RETURN_QUANTITY"]) / SUM('Sales'["FACT_SALES"."QUANTITY"]) * 100
)
        lineageTag: 85fd4974-2286-4429-958a-f351cbf349a9
        formatString: 0.00%
        displayFolder: Measures

    measure 'Budget Variance' = SUM('Sales'["FACT_SALES"."QUANTITY" * "FACT_SALES"."UNIT_PRICE"]) - SUM('Sales'["FACT_BUDGET"."BUDGET_AMOUNT"])
        lineageTag: a2b2a1a2-ad7e-483f-8a1c-09fa4c3e3982
        formatString: #,0.00
        displayFolder: Measures

        /// @migration: broken-ref-auto-hidden
