table Fact_Essbase_medium_finance
    lineageTag: db4e347c-1fed-45cc-a434-d0e1742355e9
    description: Fact table synthesised from Essbase cube data cells

    partition Fact_Essbase_medium_finance = m
        mode: import
        source
            let
                Source = 'Sql'[Database]("onelake-sql-endpoint", "EssbaseLakehouse"),
                Fact_Essbase_medium_finance = Source{[Schema="dbo", Item="Fact_Essbase_medium_finance"]}[Data]
            in
                Fact_Essbase_medium_finance

    column Value
        dataType: double
        lineageTag: caa3f9a4-2367-41f9-b697-d3bddbb5ef11
        formatString: #,0.00
        summarizeBy: sum
        description: Essbase data cell value

    measure 'Revenue' = SUM('Fact_Essbase_medium_finance'['Fact'[Revenue]])
        lineageTag: e544241a-d0a1-4e4a-84c5-55ba097c168d
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Measures

    measure 'Product Sales' = SUM('Fact_Essbase_medium_finance'['Fact'[Product Sales]])
        lineageTag: b1605cce-0084-4e8a-bec4-aa8ed6295c12
        formatString: #,0.00
        displayFolder: Measures

    measure 'Service Revenue' = SUM('Fact_Essbase_medium_finance'['Fact'[Service Revenue]])
        lineageTag: 587d6d24-7fb9-4566-96a5-15cfdb427354
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Measures

    measure 'COGS' = SUM('Fact_Essbase_medium_finance'['Fact'[COGS]])
        lineageTag: f587f0c5-eb5a-45f2-bb14-f803b7db3a8b
        formatString: #,0.00
        displayFolder: Measures

    measure 'Material Cost' = SUM('Fact_Essbase_medium_finance'['Fact'[Material Cost]])
        lineageTag: 3287fdb3-5ba3-4a8e-b6f3-21ddb83dd705
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Measures

    measure 'Labor Cost' = SUM('Fact_Essbase_medium_finance'['Fact'[Labor Cost]])
        lineageTag: 897345a9-c36d-457e-80ae-9bb6ebafb511
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Measures

    measure 'Gross Profit' = Revenue - COGS
        lineageTag: aeeeeaa3-bf70-4967-8422-3ab294ca8f03
        formatString: #,0.00
        displayFolder: Measures
        description: Dynamic calc: Revenue - COGS

    measure 'Operating Expenses' = SUM('Fact_Essbase_medium_finance'['Fact'[Operating Expenses]])
        lineageTag: 4a57ab9d-b1ae-49c8-a48e-6637ec4f1cf4
        formatString: #,0.00
        displayFolder: Measures

    measure 'Marketing' = SUM('Fact_Essbase_medium_finance'['Fact'[Marketing]])
        lineageTag: 242d7166-22c5-4973-860f-1a07fac280dc
        formatString: #,0.00
        displayFolder: Measures

    measure 'R&D' = SUM('Fact_Essbase_medium_finance'['Fact'[R&D]])
        lineageTag: 24eab8b1-9aed-4855-9fc6-00a3c012a4b3
        formatString: #,0.00
        displayFolder: Measures

    measure 'G&A' = SUM('Fact_Essbase_medium_finance'['Fact'[G&A]])
        lineageTag: bba3af97-7885-41ed-a0a5-af2a5d87c563
        formatString: #,0.00
        displayFolder: Measures

    measure 'Operating Income' = Gross Profit - Operating Expenses
        lineageTag: f4bb0902-1946-497a-aa1e-b8ef66b850e9
        formatString: #,0.00
        displayFolder: Measures
        description: Dynamic calc: Gross Profit - Operating Expenses

    measure 'Gross Margin Pct' = ROUND(Gross Profit % Revenue, 4)
        lineageTag: aebc9a5d-c66b-4d63-98f1-d56498f5aa21
        formatString: 0.00%
        displayFolder: Measures
        description: Dynamic calc: @ROUND(Gross Profit % Revenue, 4)

    measure 'CalcGrossProfit' = Revenue - COGS
        lineageTag: dcdf30b5-263e-4fe7-b94d-ff78ce42a8e2
        formatString: #,0.00
        displayFolder: Measures
        description: From Essbase calc script: CalcGrossProfit

    measure 'CalcOperatingIncome' = Gross Profit - Operating Expenses
        lineageTag: 670516d4-d3df-4c27-920e-5c8b40b508c0
        formatString: #,0.00
        displayFolder: Measures
        description: From Essbase calc script: CalcOperatingIncome

    measure 'CalcGrossMarginPct' = ROUND(Gross Profit % Revenue, 4)
        lineageTag: 090248ea-dbe4-4e2b-8786-de73e17ad862
        formatString: 0.00%
        displayFolder: Measures
        description: From Essbase calc script: CalcGrossMarginPct

    measure 'CalcVariance' = Actual - Budget
        lineageTag: e8fd36e2-a0bc-422e-8ed8-19a52d2040cd
        formatString: #,0.00
        displayFolder: Measures
        description: From Essbase calc script: CalcVariance

    measure 'CalcVariancePct' = ROUND((Actual - Budget) % Budget, 4)
        lineageTag: 1d8d7ca6-cdae-4f0b-a92e-743531d1f603
        formatString: 0.00%
        displayFolder: Measures
        description: From Essbase calc script: CalcVariancePct

    measure 'CalcYTD' = CALCULATE(SUM('Fact_Essbase_medium_finance'[/* @SUMRANGE */ Time, CALCULATE( /* @TODATE */ Time, @CURRMBR(Time])))
        lineageTag: 83c5d652-e9d0-468f-9179-11e33c6a546e
        formatString: #,0.00
        displayFolder: Measures
        description: From Essbase calc script: CalcYTD

        /// @migration: broken-ref-auto-hidden
