table Fact_Essbase_simple_budget
    lineageTag: 6135cf2e-c863-481e-a111-81888aeee6db
    description: Fact table synthesised from Essbase cube data cells

    partition Fact_Essbase_simple_budget = m
        mode: import
        source
            let
                Source = 'Sql'[Database]("onelake-sql-endpoint", "EssbaseLakehouse"),
                Fact_Essbase_simple_budget = Source{[Schema="dbo", Item="Fact_Essbase_simple_budget"]}[Data]
            in
                Fact_Essbase_simple_budget

    column Value
        dataType: double
        lineageTag: e9e0aacc-c83b-414c-822f-4c444e24f1a1
        formatString: #,0.00
        summarizeBy: sum
        description: Essbase data cell value

    measure 'Revenue' = SUM('Fact_Essbase_simple_budget'['Fact'[Revenue]])
        lineageTag: 9c3a73ce-b3e4-4969-b56d-d1ca7397be6d
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Measures

    measure 'COGS' = SUM('Fact_Essbase_simple_budget'['Fact'[COGS]])
        lineageTag: bd73c51f-cf35-4d0a-8fc6-9768f9d1b0b1
        formatString: #,0.00
        displayFolder: Measures

    measure 'Gross Profit' = Revenue - COGS
        lineageTag: 8f953742-bf97-4687-9a22-09eff3c09b33
        formatString: #,0.00
        displayFolder: Measures
        description: Dynamic calc: Revenue - COGS

    measure 'CalcGrossProfit' = Revenue - COGS
        lineageTag: 37be044c-a14f-46ec-97af-a219c6078440
        formatString: #,0.00
        displayFolder: Measures
        description: From Essbase calc script: CalcGrossProfit

        /// @migration: broken-ref-auto-hidden
