"""Data quality profiling notebook generator.

Generates a PySpark notebook template that runs data quality checks
on migrated Delta tables:  null %, distinct count, outlier detection,
type validation, and summary statistics.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


@dataclass
class DQCheck:
    """Single data quality check definition."""

    table_name: str
    column_name: str
    check_type: str  # null_pct, distinct, min_max, outlier, type_mismatch
    expected: str = ""
    threshold: float = 0.0


@dataclass
class DQProfile:
    """Data quality profile for a table."""

    table_name: str
    checks: list[DQCheck] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


@dataclass
class DQNotebook:
    """Generated DQ profiling notebook."""

    cells: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def to_notebook_json(self) -> str:
        """Generate Jupyter notebook JSON (.ipynb)."""
        nb_cells = []
        for cell_code in self.cells:
            nb_cells.append({
                "cell_type": "code",
                "source": cell_code.split("\n"),
                "metadata": {},
                "outputs": [],
                "execution_count": None,
            })
        notebook = {
            "nbformat": 4,
            "nbformat_minor": 5,
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3",
                },
                "language_info": {"name": "python", "version": "3.11"},
            },
            "cells": nb_cells,
        }
        return json.dumps(notebook, indent=2)

    @property
    def cell_count(self) -> int:
        return len(self.cells)


# ---------------------------------------------------------------------------
# Check generators
# ---------------------------------------------------------------------------

_HEADER_CELL = """# Data Quality Profiling Report
# Auto-generated by OAC-to-Fabric Migration Tool
# Run this notebook in Fabric Spark to validate migrated data quality

from pyspark.sql import functions as F
from datetime import datetime

dq_results = []
report_timestamp = datetime.now().isoformat()
print(f"DQ Profile started at {report_timestamp}")
"""

_SUMMARY_CELL = """# === DQ Summary Report ===
import json

total = len(dq_results)
passed = sum(1 for r in dq_results if r["status"] == "PASS")
failed = sum(1 for r in dq_results if r["status"] == "FAIL")
warnings = sum(1 for r in dq_results if r["status"] == "WARN")

print(f"\\n{'='*60}")
print(f"Data Quality Summary")
print(f"{'='*60}")
print(f"Total checks: {total}")
print(f"  Passed:   {passed}")
print(f"  Failed:   {failed}")
print(f"  Warnings: {warnings}")
print(f"  Pass rate: {passed/total*100:.1f}%" if total else "  No checks")
print(f"{'='*60}")

# Save results as Delta table
if dq_results:
    df = spark.createDataFrame(dq_results)
    df.write.mode("overwrite").format("delta").saveAsTable("dq_results")
    print("Results saved to dq_results table")
"""


def _null_check_cell(table_name: str, columns: list[str]) -> str:
    """Generate null percentage check cell."""
    col_checks = []
    for col in columns:
        col_checks.append(
            f'    F.round(F.sum(F.when(F.col("{col}").isNull(), 1).otherwise(0)) / F.count("*") * 100, 2).alias("{col}_null_pct")'
        )
    checks_str = ",\n".join(col_checks)

    return f'''# Null percentage check for {table_name}
df_{table_name} = spark.table("{table_name}")
null_stats = df_{table_name}.select(
{checks_str}
).collect()[0]

for col_name in {columns!r}:
    null_pct = null_stats[f"{{col_name}}_null_pct"]
    status = "PASS" if null_pct < 5 else ("WARN" if null_pct < 20 else "FAIL")
    dq_results.append({{
        "table": "{table_name}",
        "column": col_name,
        "check": "null_pct",
        "value": float(null_pct),
        "threshold": 5.0,
        "status": status,
        "timestamp": report_timestamp,
    }})
    print(f"  {{col_name}}: {{null_pct}}% null ({{status}})")
'''


def _distinct_check_cell(table_name: str, columns: list[str]) -> str:
    """Generate distinct count check cell."""
    col_checks = []
    for col in columns:
        col_checks.append(
            f'    F.countDistinct("{col}").alias("{col}_distinct")'
        )
    checks_str = ",\n".join(col_checks)

    return f'''# Distinct count check for {table_name}
total_rows = df_{table_name}.count()
distinct_stats = df_{table_name}.select(
{checks_str}
).collect()[0]

print(f"\\n{table_name}: {{total_rows}} total rows")
for col_name in {columns!r}:
    distinct = distinct_stats[f"{{col_name}}_distinct"]
    ratio = distinct / total_rows if total_rows > 0 else 0
    status = "PASS"
    if ratio < 0.01 and total_rows > 100:
        status = "WARN"  # Very low cardinality
    dq_results.append({{
        "table": "{table_name}",
        "column": col_name,
        "check": "distinct_count",
        "value": distinct,
        "threshold": 0,
        "status": status,
        "timestamp": report_timestamp,
    }})
    print(f"  {{col_name}}: {{distinct}} distinct ({{ratio:.1%}} of total)")
'''


def _row_count_cell(table_name: str) -> str:
    """Generate row count check cell."""
    return f'''# Row count check for {table_name}
row_count = df_{table_name}.count()
status = "PASS" if row_count > 0 else "FAIL"
dq_results.append({{
    "table": "{table_name}",
    "column": "*",
    "check": "row_count",
    "value": row_count,
    "threshold": 1,
    "status": status,
    "timestamp": report_timestamp,
}})
print(f"{table_name}: {{row_count}} rows ({{status}})")
'''


def _outlier_check_cell(table_name: str, numeric_columns: list[str]) -> str:
    """Generate IQR-based outlier detection cell."""
    if not numeric_columns:
        return f"# No numeric columns to check for outliers in {table_name}"

    return f'''# Outlier detection (IQR method) for {table_name}
for col_name in {numeric_columns!r}:
    quantiles = df_{table_name}.approxQuantile(col_name, [0.25, 0.75], 0.05)
    if len(quantiles) == 2 and quantiles[0] is not None:
        q1, q3 = quantiles
        iqr = q3 - q1
        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr
        outlier_count = df_{table_name}.filter(
            (F.col(col_name) < lower) | (F.col(col_name) > upper)
        ).count()
        total = df_{table_name}.count()
        pct = (outlier_count / total * 100) if total else 0
        status = "PASS" if pct < 5 else ("WARN" if pct < 15 else "FAIL")
        dq_results.append({{
            "table": "{table_name}",
            "column": col_name,
            "check": "outlier_pct",
            "value": round(pct, 2),
            "threshold": 5.0,
            "status": status,
            "timestamp": report_timestamp,
        }})
        print(f"  {{col_name}}: {{outlier_count}} outliers ({{pct:.1f}}%) — IQR [{{lower:.2f}}, {{upper:.2f}}]")
'''


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

_NUMERIC_TYPES = frozenset({
    "int", "integer", "bigint", "smallint", "tinyint",
    "float", "double", "decimal", "numeric", "number",
    "real", "money", "int64", "float64",
})


def generate_dq_notebook(
    table_inventory: list[dict],
    include_outliers: bool = True,
) -> DQNotebook:
    """Generate a complete DQ profiling notebook.

    Args:
        table_inventory: List of table dicts, each with:
            - name (str): Table name
            - columns (list[dict]): Each with name, data_type
        include_outliers: Whether to add outlier detection cells

    Returns:
        DQNotebook with generated cells
    """
    notebook = DQNotebook()
    notebook.cells.append(_HEADER_CELL)

    for table in table_inventory:
        table_name = table.get("name", "")
        if not table_name:
            continue

        columns = table.get("columns", [])
        col_names = [c.get("name", "") for c in columns if c.get("name")]
        numeric_cols = [
            c.get("name", "")
            for c in columns
            if c.get("data_type", "").lower() in _NUMERIC_TYPES and c.get("name")
        ]

        if not col_names:
            notebook.warnings.append(f"Table {table_name}: no columns found")
            continue

        # Row count
        notebook.cells.append(_row_count_cell(table_name))

        # Null checks
        notebook.cells.append(_null_check_cell(table_name, col_names))

        # Distinct counts
        notebook.cells.append(_distinct_check_cell(table_name, col_names))

        # Outlier detection for numeric columns
        if include_outliers and numeric_cols:
            notebook.cells.append(_outlier_check_cell(table_name, numeric_cols))

    # Summary cell
    notebook.cells.append(_SUMMARY_CELL)

    logger.info(
        "Generated DQ notebook: %d cells for %d tables",
        notebook.cell_count, len(table_inventory),
    )
    return notebook
