table 'Calendar'
	lineageTag: be9b7802-1c83-4531-9e7f-949cd3f31051
	isHidden

	annotation Copilot_TableDescription = Auto-generated Calendar table for time intelligence
	annotation Copilot_DateTable = YES

	partition 'Calendar' = m
		mode: import
		source =
				let
				    StartDate = Date.StartOfYear(List.Min(#"Time"[Date])),
				    EndDate = Date.EndOfYear(List.Max(#"Time"[Date])),
				    DateList = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1,0,0,0)),
				    #"Convert to Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Convert to Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date]), type text),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date]), type text)
				in
				    #"Added DayName"

	column Date
		dataType: dateTime
		lineageTag: 9436d306-239a-4287-9316-12b85f9a5754
		formatString: yyyy-MM-dd
		sourceColumn: Date
		summarizeBy: none

	column Year
		dataType: int64
		lineageTag: e581f2c1-97e0-4c74-b4aa-8ed7f3696ea3
		formatString: 0
		sourceColumn: Year
		summarizeBy: none

	column Quarter
		dataType: int64
		lineageTag: db2c1ec2-5534-4638-8fc9-b206a83cfc91
		formatString: 0
		sourceColumn: Quarter
		summarizeBy: none

	column Month
		dataType: int64
		lineageTag: 23ff1c63-e129-48b2-ba96-3be93772d3f8
		formatString: 0
		sourceColumn: Month
		summarizeBy: none

	column MonthName
		dataType: string
		lineageTag: 8f3589c3-f3a8-4532-8107-a2dd9f1a8b50
		sourceColumn: MonthName
		sortByColumn: Month
		summarizeBy: none

	column Day
		dataType: int64
		lineageTag: 417e79d5-b1c9-42c3-bae6-d723600d6f2f
		formatString: 0
		sourceColumn: Day
		summarizeBy: none

	column DayOfWeek
		dataType: int64
		lineageTag: 851345e3-9057-46f5-8531-e18ef7441180
		formatString: 0
		sourceColumn: DayOfWeek
		summarizeBy: none

	column DayName
		dataType: string
		lineageTag: c0701c21-7011-4194-a788-db737da2106c
		sourceColumn: DayName
		sortByColumn: DayOfWeek
		summarizeBy: none

	hierarchy 'Date Hierarchy'
		lineageTag: fdfb867c-3cf2-4fee-b21a-cd2ec855dd45
		level Year
			lineageTag: ce8fb48c-55a2-40a8-9d1c-4cacf2847cd2
			column: Year
		level Quarter
			lineageTag: c7843f69-f823-4980-978c-37deab2c761e
			column: Quarter
		level Month
			lineageTag: 1ce32ab1-3705-4a1f-a3fa-d1fe93062d4a
			column: Month
		level Day
			lineageTag: b3c41086-5b82-4c1b-9ee0-871c84f336e7
			column: Day

	measure 'YTD Sales' = TOTALYTD(SUM('Calendar'[Date]), 'Calendar'[Date])
		lineageTag: 40cf7b79-f04a-4f1a-a918-fd5ac44ca24d
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence

	measure 'PY Sales' = CALCULATE([YTD Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
		lineageTag: 09d343b1-e16f-411f-8362-a328b4cb3bf4
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Time Intelligence

	measure 'YoY %' = DIVIDE([YTD Sales] - [PY Sales], [PY Sales], BLANK())
		lineageTag: 2d4ce314-5007-4254-9a94-ffdca149840c
		formatString: 0.00%
		displayFolder: Time Intelligence

	annotation __migration_note = unreferenced-hidden — consider removing
