table FACT_Orders
    lineageTag: 3301db6f-c876-4bc8-9234-4676fb908f89

    partition FACT_Orders = m
        mode: import
        source
            let
                Source = Sql.Database("onelake-sql-endpoint", "MigrationLakehouse"),
                FACT_Orders = Source{[Schema="dbo", Item="FACT_Orders"]}[Data]
            in
                FACT_Orders

    column 'Order ID' = "ORDERS"."ORDER_ID"
        dataType: string
        lineageTag: 66d84518-a0ba-41d4-953a-85d8d03a2e38

    column 'Order Amount' = "ORDERS"."AMOUNT"
        dataType: string
        lineageTag: c7170fec-94a6-4f40-a5e6-65b5501c4bfa

    measure 'Profit' = SUM('FACT_Orders'["ORDERS"."AMOUNT"]) * 0.2
        lineageTag: ac84a243-6d60-493c-846c-de05c1d021d6
        formatString: #,0.00
        displayFolder: Measures
