table FACT_Payroll
    lineageTag: a1d7b508-9a45-4564-9fb7-0e0922148fe8

    partition FACT_Payroll = m
        mode: import
        source
            let
                Source = Sql.Database("onelake-sql-endpoint", "MigrationLakehouse"),
                FACT_Payroll = Source{[Schema="dbo", Item="FACT_Payroll"]}[Data]
            in
                FACT_Payroll

    column 'Pay ID' = "PAYROLL"."PAY_ID"
        dataType: string
        lineageTag: 5865e327-ad1e-47f4-86ee-e063bd98b211

    column 'Gross Pay' = "PAYROLL"."GROSS_PAY"
        dataType: string
        lineageTag: dc03fc36-d040-40c5-9f78-28e6dccc7ee9

    column 'Net Pay' = "PAYROLL"."GROSS_PAY" - "PAYROLL"."DEDUCTIONS"
        dataType: string
        lineageTag: 6f7877e8-430b-468a-a080-be96caf99f35

    measure 'Avg Salary' = AVERAGE('FACT_Payroll'["EMPLOYEES"."SALARY"])
        lineageTag: ad256b47-7084-46f1-92fb-a861ee7a25fe
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Measures
