table FACT_Payroll
    lineageTag: eb7e9085-b342-4685-a7f2-9869dd2a253e

    partition FACT_Payroll = m
        mode: import
        source
            let
                Source = 'Sql'[Database]("onelake-sql-endpoint", "MigrationLakehouse"),
                FACT_Payroll = Source{[Schema="dbo", Item="FACT_Payroll"]}[Data]
            in
                FACT_Payroll

    column 'Pay ID' = "PAYROLL"."PAY_ID"
        dataType: string
        lineageTag: 876a2db5-a634-4374-9aad-ddf74bc313d3

    column 'Gross Pay' = "PAYROLL"."GROSS_PAY"
        dataType: string
        lineageTag: f894c6ad-fde3-40d2-942f-1b255c82ad9e

    column 'Net Pay' = "PAYROLL"."GROSS_PAY" - "PAYROLL"."DEDUCTIONS"
        dataType: string
        lineageTag: c6810220-dc01-4306-922d-7ba229f23b7b

    measure 'Avg Salary' = AVERAGE('FACT_Payroll'["EMPLOYEES"."SALARY"])
        lineageTag: c92fd91b-f377-4b7a-88bc-d54bc1bebe5a
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Measures

        /// @migration: broken-ref-auto-hidden
