table FACT_Orders
    lineageTag: 1131fd40-b700-40d5-a243-c9b8f0b4b60a

    partition FACT_Orders = m
        mode: import
        source
            let
                Source = 'Sql'[Database]("onelake-sql-endpoint", "MigrationLakehouse"),
                FACT_Orders = Source{[Schema="dbo", Item="FACT_Orders"]}[Data]
            in
                FACT_Orders

    column 'Order ID' = "ORDERS"."ORDER_ID"
        dataType: string
        lineageTag: cbabfc27-b026-4123-a5cc-975685c0b92d

    column 'Order Amount' = "ORDERS"."AMOUNT"
        dataType: string
        lineageTag: d72c68e9-59df-48e0-9d9e-fba32d0e5d5d

    measure 'FACT_Orders_Profit' = SUM('FACT_Orders'["ORDERS"."AMOUNT"]) * 0.2
        lineageTag: 3c7c9dad-5dd2-41c7-a68f-0b0d7f559a1d
        formatString: #,0.00
        displayFolder: Measures

        /// @migration: broken-ref-auto-hidden
