table FACT_Orders
    lineageTag: 6e067a41-03ac-4582-8327-077174f99230

    partition FACT_Orders = m
        mode: import
        source
            let
                Source = Sql.Database("onelake-sql-endpoint", "MigrationLakehouse"),
                FACT_Orders = Source{[Schema="dbo", Item="FACT_Orders"]}[Data]
            in
                FACT_Orders

    column 'Order ID' = "ORDERS"."ORDER_ID"
        dataType: string
        lineageTag: 274d67aa-e63e-446d-9b58-afd297a98123

    column 'Order Amount' = "ORDERS"."AMOUNT"
        dataType: string
        lineageTag: 8e21ec6a-29c7-4b16-af48-98fc0fa8ce69

    measure 'Profit' = SUM('FACT_Orders'["ORDERS"."AMOUNT"]) * 0.2
        lineageTag: 774ec189-3994-483b-b436-2467f3a39832
        formatString: #,0.00
        displayFolder: Measures
