table FACT_Orders
    lineageTag: 5fe3b33d-bd12-4384-8829-a3b420c80063

    partition FACT_Orders = m
        mode: import
        source
            let
                Source = 'Sql'[Database]("onelake-sql-endpoint", "MigrationLakehouse"),
                FACT_Orders = Source{[Schema="dbo", Item="FACT_Orders"]}[Data]
            in
                FACT_Orders

    column 'Order ID' = "ORDERS"."ORDER_ID"
        dataType: string
        lineageTag: 648531d5-d51f-4c4b-a1cf-a45cbac7720b

    column 'Order Amount' = "ORDERS"."AMOUNT"
        dataType: string
        lineageTag: 8ce5b9e4-c534-4b4e-b2eb-544ea383df67

    measure 'FACT_Orders_Profit' = SUM('FACT_Orders'["ORDERS"."AMOUNT"]) * 0.2
        lineageTag: 0d9b03bb-5184-4c83-a328-28a7d96b7219
        formatString: #,0.00
        displayFolder: Measures

        /// @migration: broken-ref-auto-hidden
