table FACT_Payroll
    lineageTag: 9065b9c9-6603-4c33-b675-f47399d5f743

    partition FACT_Payroll = m
        mode: import
        source
            let
                Source = Sql.Database("onelake-sql-endpoint", "MigrationLakehouse"),
                FACT_Payroll = Source{[Schema="dbo", Item="FACT_Payroll"]}[Data]
            in
                FACT_Payroll

    column 'Pay ID' = "PAYROLL"."PAY_ID"
        dataType: string
        lineageTag: a439e680-96d8-40bf-8bfe-f1ece89402b2

    column 'Gross Pay' = "PAYROLL"."GROSS_PAY"
        dataType: string
        lineageTag: 659e6e93-cb0b-4a29-b626-8a85adf20840

    column 'Net Pay' = "PAYROLL"."GROSS_PAY" - "PAYROLL"."DEDUCTIONS"
        dataType: string
        lineageTag: f94deae8-5ba9-4d63-8cc6-b9ea79b11a02

    measure 'Avg Salary' = AVERAGE('FACT_Payroll'["EMPLOYEES"."SALARY"])
        lineageTag: 81fc9e58-fe2b-40d3-9523-0e2027e8c1cf
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Measures
