table FACT_Orders
    lineageTag: 66a87fe3-a47d-4df3-98cf-21468e8c7f1f

    partition FACT_Orders = m
        mode: import
        source
            let
                Source = 'Sql'[Database]("onelake-sql-endpoint", "MigrationLakehouse"),
                FACT_Orders = Source{[Schema="dbo", Item="FACT_Orders"]}[Data]
            in
                FACT_Orders

    column 'Order ID' = "ORDERS"."ORDER_ID"
        dataType: string
        lineageTag: ee783a77-db29-43f2-bcb5-5521fac04daa

    column 'Order Amount' = "ORDERS"."AMOUNT"
        dataType: string
        lineageTag: 0c1e1827-be4e-4282-a950-11fba253f537

    measure 'FACT_Orders_Profit' = SUM('FACT_Orders'["ORDERS"."AMOUNT"]) * 0.2
        lineageTag: cbd1b734-5e52-443d-9ff6-1c070c4a84c5
        formatString: #,0.00
        displayFolder: Measures

        /// @migration: broken-ref-auto-hidden
