table FACT_Payroll
    lineageTag: 9ad6cea6-fb20-474e-bb5c-634eef2c0ee2

    partition FACT_Payroll = m
        mode: import
        source
            let
                Source = Sql.Database("onelake-sql-endpoint", "MigrationLakehouse"),
                FACT_Payroll = Source{[Schema="dbo", Item="FACT_Payroll"]}[Data]
            in
                FACT_Payroll

    column 'Pay ID' = "PAYROLL"."PAY_ID"
        dataType: string
        lineageTag: b7b7a177-ce94-498c-ac06-f003a06edb9b

    column 'Gross Pay' = "PAYROLL"."GROSS_PAY"
        dataType: string
        lineageTag: 7150e80b-34ce-4ae0-83d9-400929544f37

    column 'Net Pay' = "PAYROLL"."GROSS_PAY" - "PAYROLL"."DEDUCTIONS"
        dataType: string
        lineageTag: 6f8e7426-fa12-4037-bcc4-04e9e67610a6

    measure 'Avg Salary' = AVERAGE('FACT_Payroll'["EMPLOYEES"."SALARY"])
        lineageTag: d0441844-5eae-4367-9c94-1aa0932f70f5
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Measures
