table General_Ledger
    lineageTag: a4f8fc5d-dd71-45cd-8d1c-e2e61dc3dfce

    partition General_Ledger = m
        mode: import
        source
            let
                Source = 'Sql'[Database]("onelake-sql-endpoint", "MigrationLakehouse"),
                General_Ledger = Source{[Schema="dbo", Item="General_Ledger"]}[Data]
            in
                General_Ledger

    measure 'Net Amount' = SUM('General_Ledger'["FACT_GL"."DEBIT_AMOUNT"]) - SUM('General_Ledger'["FACT_GL"."CREDIT_AMOUNT"])
        lineageTag: 1edad4b4-b2ff-40d9-bfcd-34653b7ff1bf
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Measures

    measure 'Converted Amount' = SUM('General_Ledger'["FACT_GL"."DEBIT_AMOUNT" * "FACT_GL"."EXCHANGE_RATE"])
        lineageTag: ea53142d-82d1-4c02-a4ef-48b807faaeeb
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Measures

    measure 'General_Ledger_Budget Variance' = SUM('General_Ledger'["FACT_GL"."DEBIT_AMOUNT"]) - SUM('General_Ledger'["FACT_BUDGET"."BUDGET_AMOUNT"])
        lineageTag: d507dee4-a482-4e1c-abba-2fcaaa7a70f6
        formatString: #,0.00
        displayFolder: Measures

    measure 'Budget Variance Pct' = SWITCH(TRUE(),
    SUM('General_Ledger'["FACT_BUDGET"."BUDGET_AMOUNT"]) = 0, 0,
    (SUM('General_Ledger'["FACT_GL"."DEBIT_AMOUNT"]) - SUM('General_Ledger'["FACT_BUDGET"."BUDGET_AMOUNT"])) / SUM('General_Ledger'["FACT_BUDGET"."BUDGET_AMOUNT"]) * 100
)
        lineageTag: 41808061-4db4-4efb-934f-65821e5927f3
        formatString: 0.00%
        displayFolder: Measures

    measure 'Top N Accounts' = TOPN(10, 'General_Ledger', SUM('General_Ledger'["FACT_GL"."DEBIT_AMOUNT"]))
        lineageTag: 6f00bb76-22c9-47db-8ad0-7440100f58c9
        formatString: #,0.00
        displayFolder: Measures

        /// @migration: broken-ref-auto-hidden
