table 'Calendar'
    lineageTag: 49c1eedd-7872-4712-842e-52b8d661a2e9
    description: Auto-generated Calendar table for time intelligence
    isHidden

    partition 'Calendar' = m
        mode: import
        source
            let
                StartDate = 'Date'[StartOfYear]('List'[Min]('Dim Customer'[Created Date])),
                EndDate = 'Date'[EndOfYear]('List'[Max]('Dim Customer'[Created Date])),
                DateList = 'List'[Dates](StartDate, 'Duration'[Days](EndDate - StartDate) + 1, #duration(1,0,0,0)),
                #"Convert to Table" = 'Table'[FromList](DateList, 'Splitter'[SplitByNothing](), {{"Date"}}),
                #"Changed Type" = 'Table'[TransformColumnTypes](#"Convert to Table", {{"Date", type date}}),
                #"Added Year" = 'Table'[AddColumn](#"Changed Type", "Year", each 'Date'[Year]([Date]), 'Int64'[Type]),
                #"Added Quarter" = 'Table'[AddColumn](#"Added Year", "Quarter", each 'Date'[QuarterOfYear]([Date]), 'Int64'[Type]),
                #"Added Month" = 'Table'[AddColumn](#"Added Quarter", "Month", each 'Date'[Month]([Date]), 'Int64'[Type]),
                #"Added MonthName" = 'Table'[AddColumn](#"Added Month", "MonthName", each 'Date'[MonthName]([Date]), type text),
                #"Added Day" = 'Table'[AddColumn](#"Added MonthName", "Day", each 'Date'[Day]([Date]), 'Int64'[Type]),
                #"Added DayOfWeek" = 'Table'[AddColumn](#"Added Day", "DayOfWeek", each 'Date'[DayOfWeek]([Date], 'Day'[Monday]) + 1, 'Int64'[Type]),
                #"Added DayName" = 'Table'[AddColumn](#"Added DayOfWeek", "DayName", each 'Date'[DayOfWeekName]([Date]), type text)
            in
                #"Added DayName"

    column Date
        dataType: dateTime
        lineageTag: a7dced3d-dbda-40e4-9d9c-cdc4bc7c1aef
        formatString: yyyy-MM-dd
        sourceColumn: Date
        summarizeBy: none

    column Year
        dataType: int64
        lineageTag: 7deab879-df22-4413-ac90-dd81803dfb0b
        formatString: 0
        sourceColumn: Year
        summarizeBy: none

    column Quarter
        dataType: int64
        lineageTag: a15ff742-94ee-4d84-81e4-42145acb67af
        formatString: 0
        sourceColumn: Quarter
        summarizeBy: none

    column Month
        dataType: int64
        lineageTag: c1a45d9b-ad1f-4db3-b220-72217fa028c4
        formatString: 0
        sourceColumn: Month
        summarizeBy: none

    column MonthName
        dataType: string
        lineageTag: 811ce4fb-3a93-4108-9211-245a1735ce4e
        sourceColumn: MonthName
        sortByColumn: Month
        summarizeBy: none

    column Day
        dataType: int64
        lineageTag: 9ddc077e-604b-45e1-aa7a-974f00ca15bd
        formatString: 0
        sourceColumn: Day
        summarizeBy: none

    column DayOfWeek
        dataType: int64
        lineageTag: 8dd71ae0-d131-4db2-9379-fe3e5460a1cf
        formatString: 0
        sourceColumn: DayOfWeek
        summarizeBy: none

    column DayName
        dataType: string
        lineageTag: e5ba6fad-f2c3-4fa5-ad79-27469d1f7d6b
        sourceColumn: DayName
        sortByColumn: DayOfWeek
        summarizeBy: none

    hierarchy 'Date Hierarchy'
        lineageTag: cf0cf178-8af3-4438-8c8f-32980453b114
        level Year
            lineageTag: 910acfc3-cb9a-48fc-b2f3-54309e012f24
            column: Year
        level Quarter
            lineageTag: 77b75293-a3a6-4a02-981f-946aa0fc7d79
            column: Quarter
        level Month
            lineageTag: fe6520af-2eb1-4bf8-82bf-52ee3ddbd7a0
            column: Month
        level Day
            lineageTag: 1bfccf28-0fcf-4122-88af-b5824635d0c8
            column: Day

    measure 'YTD Sales' = TOTALYTD(SUM('Calendar'[Date]), 'Calendar'[Date])
        lineageTag: 8b8e4cf4-6256-4e04-8bfa-b6c0375922b3
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Time Intelligence
        description: YTD aggregate — replace SUM('Calendar'[Date]) with your actual measure

    measure 'PY Sales' = CALCULATE([YTD Sales], SAMEPERIODLASTYEAR('Calendar'[Date]))
        lineageTag: 55047d09-2e65-4ae7-b241-373d2a2f05d6
        formatString: \$#,0.00;(\$#,0.00);\$#,0.00
        displayFolder: Time Intelligence
        description: Prior Year — references YTD Sales measure

    measure 'YoY %' = DIVIDE([YTD Sales] - [PY Sales], [PY Sales], BLANK())
        lineageTag: 6dff9f9a-bf33-41c1-ad65-8df978e4e7c0
        formatString: 0.00%
        displayFolder: Time Intelligence
        description: Year-over-Year percentage change

    /// @migration: unreferenced-hidden — consider removing
