"""Domain models for the OAC-to-Fabric migration framework."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class AssetType(str, Enum):
    """Types of OAC assets that can be discovered."""

    ANALYSIS = "analysis"
    DASHBOARD = "dashboard"
    DATA_MODEL = "dataModel"
    PROMPT = "prompt"
    FILTER = "filter"
    AGENT_ALERT = "agent"
    DATA_FLOW = "dataflow"
    CONNECTION = "connection"
    SUBJECT_AREA = "subjectArea"
    PHYSICAL_TABLE = "physicalTable"
    LOGICAL_TABLE = "logicalTable"
    PRESENTATION_TABLE = "presentationTable"
    SECURITY_ROLE = "securityRole"
    INIT_BLOCK = "initBlock"


class ComplexityCategory(str, Enum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"


class MigrationStatus(str, Enum):
    NOT_STARTED = "not-started"
    IN_PROGRESS = "in-progress"
    COMPLETED = "completed"
    FAILED = "failed"
    BLOCKED = "blocked"


class AgentState(str, Enum):
    IDLE = "idle"
    DISCOVERING = "discovering"
    PLANNING = "planning"
    EXECUTING = "executing"
    VALIDATING = "validating"
    DONE = "done"
    FAILED = "failed"


class TaskStatus(str, Enum):
    PENDING = "pending"
    ASSIGNED = "assigned"
    IN_PROGRESS = "in-progress"
    VALIDATING = "validating"
    COMPLETED = "completed"
    FAILED = "failed"
    RETRYING = "retrying"
    BLOCKED = "blocked"


# ---------------------------------------------------------------------------
# Migration scope
# ---------------------------------------------------------------------------

class MigrationScope(BaseModel):
    """Defines which OAC assets are in scope for migration."""

    include_paths: list[str] = Field(default_factory=list, description="OAC catalog paths to include (glob patterns)")
    exclude_paths: list[str] = Field(default_factory=list, description="OAC catalog paths to exclude")
    asset_types: list[AssetType] = Field(default_factory=list, description="Asset types to include (empty = all)")
    wave: int | None = Field(default=None, description="Migration wave number")


# ---------------------------------------------------------------------------
# Dependency
# ---------------------------------------------------------------------------

class Dependency(BaseModel):
    """A directed dependency from one asset to another."""

    source_id: str
    target_id: str
    dependency_type: str = Field(description="e.g. 'uses_subject_area', 'embeds_analysis', 'reads_table'")


# ---------------------------------------------------------------------------
# Inventory item
# ---------------------------------------------------------------------------

class InventoryItem(BaseModel):
    """A single discovered OAC asset."""

    id: str = Field(description="Unique deterministic ID derived from asset path")
    asset_type: AssetType
    source_path: str = Field(description="Full OAC catalog path")
    name: str
    owner: str = ""
    last_modified: datetime | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)
    dependencies: list[Dependency] = Field(default_factory=list)
    complexity_score: float = 0.0
    complexity_category: ComplexityCategory = ComplexityCategory.LOW
    migration_status: MigrationStatus = MigrationStatus.NOT_STARTED
    migration_wave: int | None = None
    incomplete: bool = False
    discovered_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    source: str = Field(default="api", description="'api' or 'rpd'")

    def to_flat_dict(self) -> dict[str, Any]:
        """Flatten for Delta table storage (JSON-encode nested fields)."""
        d = self.model_dump(mode="json")
        d["metadata"] = json.dumps(d["metadata"])
        d["dependencies"] = json.dumps(d["dependencies"])
        return d


# ---------------------------------------------------------------------------
# Aggregated results
# ---------------------------------------------------------------------------

class Inventory(BaseModel):
    """Collection of discovered assets."""

    items: list[InventoryItem] = Field(default_factory=list)
    discovered_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def count(self) -> int:
        return len(self.items)

    def by_type(self, asset_type: AssetType) -> list[InventoryItem]:
        return [i for i in self.items if i.asset_type == asset_type]


class MigrationPlan(BaseModel):
    """A plan generated by an agent for migrating assets."""

    agent_id: str
    wave: int = 1
    items: list[InventoryItem] = Field(default_factory=list)
    estimated_duration_minutes: int = 0
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class MigrationResult(BaseModel):
    """Result of executing a migration plan."""

    agent_id: str
    wave: int = 1
    total: int = 0
    succeeded: int = 0
    failed: int = 0
    skipped: int = 0
    errors: list[dict[str, Any]] = Field(default_factory=list)
    started_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    completed_at: datetime | None = None


class ValidationReport(BaseModel):
    """Validation results from an agent."""

    agent_id: str
    total_checks: int = 0
    passed: int = 0
    failed: int = 0
    warnings: int = 0
    details: list[dict[str, Any]] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class RollbackResult(BaseModel):
    """Result of a rollback operation."""

    agent_id: str
    rolled_back: int = 0
    errors: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Agent task (coordination table row)
# ---------------------------------------------------------------------------

class AgentTask(BaseModel):
    """A task assigned to an agent, stored in the agent_tasks Delta table."""

    id: str
    agent_id: str
    wave_id: str = ""
    task_type: str
    status: TaskStatus = TaskStatus.PENDING
    asset_type: str = ""
    asset_source_name: str = ""
    asset_target_name: str = ""
    started_at: datetime | None = None
    completed_at: datetime | None = None
    duration_ms: int | None = None
    retry_count: int = 0
    result: dict[str, Any] = Field(default_factory=dict)
    assigned_by: str = "orchestrator"
    last_updated: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
