"""
Fabric Notebook: Budget Calculations
Source: Essbase longview_budget_writeback/longview_budget_writeback
Replaces: Essbase calc scripts (AGG, ALLOCATE, @TODATE)
Generated by OAC-to-Fabric Migration Agent
"""

from pyspark.sql import functions as F
from pyspark.sql.window import Window
from delta.tables import DeltaTable
import logging

logger = logging.getLogger(__name__)

# ── Parameters (set by pipeline) ───────────────────────────
SCENARIO = spark.conf.get("spark.scenario", "Budget")
FISCAL_YEAR = int(spark.conf.get("spark.fiscal_year", "2026"))

# ── Step 1: Read writeback input ───────────────────────────
budget_input = (
    spark.read.format("delta")
    .load("Tables/Budget_Input")
    .filter(F.col("Scenario") == SCENARIO)
)
logger.info(f"Read {budget_input.count()} budget rows")

# ── Step 2: AGG — Aggregate to parent entities ────────────
# Replaces: AGG(Entity)
entity_hier = spark.read.format("delta").load("Tables/Dim_Entity")

aggregated = (
    budget_input
    .join(entity_hier, "Entity")
    .groupBy("ParentEntity", "Period", "Product", "Scenario", "Currency")
    .agg(F.sum("Revenue").alias("Revenue"))
    .withColumnRenamed("ParentEntity", "Entity")
    .withColumn("CalcSource", F.lit("agg"))
)

# ── Step 3: @ALLOCATE — Proportional allocation ───────────
# Replaces: @ALLOCATE / @MDALLOCATE
actuals = spark.read.format("delta").load("Tables/Fact_Actuals")

# Calculate allocation weights from actuals
total_window = Window.partitionBy()
revenue_weights = (
    actuals
    .filter(F.col("Account") == "Revenue")
    .groupBy("Entity")
    .agg(F.sum("Revenue").alias("Revenue"))
    .withColumn("Weight", F.col("Revenue") / F.sum("Revenue").over(total_window))
)

# Allocate corporate overhead proportionally
overhead = budget_input.filter(
    F.col("Account") == "Corporate_Overhead"
)
allocated = (
    overhead.crossJoin(revenue_weights)
    .withColumn("Revenue", F.col("Revenue") * F.col("Weight"))
    .select("Period", "Entity", "Product", "Scenario", "Currency", "Revenue")
    .withColumn("CalcSource", F.lit("allocation"))
)

# ── Step 4: @TODATE — Year-to-date accumulation ──────────
# Replaces: @SUMRANGE / @TODATE
ytd_window = Window.partitionBy("Entity", "Product", "Scenario", "Currency").orderBy("Period").rowsBetween(Window.unboundedPreceding, 0)

budget_ytd = budget_input.withColumn(
    "Revenue_YTD", F.sum("Revenue").over(ytd_window)
)

# ── Step 5: Currency conversion ───────────────────────────
fx_rates = spark.read.format("delta").load("Tables/FX_Rates")
budget_converted = (
    budget_input
    .join(fx_rates, "Currency")
    .withColumn("Revenue_USD", F.col("Revenue") * F.col("Rate"))
)

# ── Final: Write to Gold layer ────────────────────────────
budget_input_tagged = budget_input.withColumn("CalcSource", F.lit("input"))

final = budget_input_tagged
final = final.unionByName(aggregated, allowMissingColumns=True)
final = final.unionByName(allocated, allowMissingColumns=True)

(
    final.write.format("delta")
    .mode("overwrite")
    .option("mergeSchema", "true")
    .save("Tables/Budget_Consolidated")
)

logger.info(f"Wrote {final.count()} rows to Budget_Consolidated")