-- ============================================
-- Writeback tables for: longview_budget_writeback
-- Source: Essbase longview_budget_writeback/longview_budget_writeback
-- Generated by OAC-to-Fabric Migration Agent
-- ============================================

IF OBJECT_ID('dbo.Budget_Input', 'U') IS NULL
CREATE TABLE dbo.Budget_Input (
    [Period] INT NOT NULL,
    [Entity] NVARCHAR(100) NOT NULL,
    [Product] NVARCHAR(100) NOT NULL,
    [Scenario] NVARCHAR(100) NOT NULL,
    [Currency] NVARCHAR(100) NOT NULL,
    [Revenue] DECIMAL(18,2),
    [Gross_Revenue] DECIMAL(18,2),
    [Returns] DECIMAL(18,2),
    [COGS] DECIMAL(18,2),
    [Gross_Margin] DECIMAL(18,2),
    [ModifiedBy] NVARCHAR(100) DEFAULT CURRENT_USER,
    [ModifiedAt] DATETIME2 DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_Budget_Input PRIMARY KEY NONCLUSTERED ([Period], [Entity], [Product], [Scenario], [Currency]) NOT ENFORCED
);

IF OBJECT_ID('dbo.Budget_Consolidated', 'U') IS NULL
CREATE TABLE dbo.Budget_Consolidated (
    [Period] INT NOT NULL,
    [Entity] NVARCHAR(100) NOT NULL,
    [Product] NVARCHAR(100) NOT NULL,
    [Scenario] NVARCHAR(100) NOT NULL,
    [Currency] NVARCHAR(100) NOT NULL,
    [Revenue] DECIMAL(18,2),
    [Gross_Revenue] DECIMAL(18,2),
    [Returns] DECIMAL(18,2),
    [COGS] DECIMAL(18,2),
    [Gross_Margin] DECIMAL(18,2),
    [CalcSource] NVARCHAR(50) DEFAULT 'input',
    [LastCalcAt] DATETIME2 DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('dbo.Budget_Audit', 'U') IS NULL
CREATE TABLE dbo.Budget_Audit (
    [AuditId] BIGINT IDENTITY(1,1),
    [Period] INT,
    [Entity] NVARCHAR(100),
    [Product] NVARCHAR(100),
    [Scenario] NVARCHAR(100),
    [Currency] NVARCHAR(100),
    [OldAmount] DECIMAL(18,2),
    [NewAmount] DECIMAL(18,2),
    [ChangedBy] NVARCHAR(100),
    [ChangedAt] DATETIME2 DEFAULT SYSUTCDATETIME()
);
